### ISSUE TITLE
Issues with analyze.sh

### ISSUE THREAD

**Issue by erb24** [pgromano/B_form_parameters#1]
I could be doing something stupid when running the script, but I encounter two errors when analyzing the trinucleotides:

1) When using trjcat to concatenate the trajectories, it cannot read the user input (settime.inp) because there are underscores before the start times in settime.inp (e.g. _0 when it should be 0).

2) There is no ${sys}.gro file generated by anything _a priori_, so there is nothing for _index.f08 to read.

The .txt file I attached (when save as an .sh file; Github doesn't allow for a .sh file to be an attachment) seems to work correctly and without errors.
[analyze.txt](https://github.com/pgromano/B_form_parameters/files/1556568/analyze.txt)

**Comment by pgromano** [comment]
1. The file `settime.py` is setup by default to work with dinucleotides. You just need to edit the number in the index slicing to increase by the number of additional nucleotides. I believe Tomas should have that already set up. I helped him set it up a few times...
1.  No there is not a `${sys}.gro` file. Since the simulations output that already, I didn't see the need.

**Comment by erb24** [comment]
Eh.
